apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: khozar-com-tls1
spec:
  secretName: khozar-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: khozar.com
  dnsNames:
    - multik8s.khozar.com
